<Project Sdk="Aspire.AppHost.Sdk/13.1.0">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Elasticsearch" Version="13.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Play.Catalog\Play.Catalog.csproj" />
    <ProjectReference Include="..\Play.Identity\Play.Identity.csproj" />
    <ProjectReference Include="..\Play.Payment\Play.Payment.csproj" />
  </ItemGroup>

</Project>

